language: objective-c
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - gem install compass --version "=0.12.3"
  - npm install -g grunt-cli
install: npm install
before_script: grunt dist